apiVersion: v1
kind: Pod
metadata:
  name: rediss-app-pod
  labels:
    name: rediss-app-pod
    app: demo-voting-app

spec:
  containers:
  - name: rediss-app
    image: redis
    ports:
    - containerPort: 6379